codex-team/hawk.api.nodejs

src/directives/requireAuthDirective.js
src/index.js
src/resolvers/user.js
src/typeDefs/schema.graphql
src/typeDefs/user.graphql

Украшалка, которая сделает схему более декларативной, а код без повторений

Require auth directive

---

.eslintrc.js
.huskyrc.js
.lintstagedrc.js
package.json
yarn.lock

Удалены ненужные правила из eslint config
Добавлен автоматический линтинг при коммите

eslint-setup

---

docker-compose.dev.yml
docker-compose.prod.yml

* add `depends_on` setting for mongo loading priority

Docker compose fix

---

DOCKER.md
app.js
docker-compose.dev.yml
package.json
src/directives/requireAuthDirective.js
src/errors.js
src/index.js
src/models/user.js
src/resolvers/user.js
src/resolvers/workspace.js
src/typeDefs/user.graphql
yarn.lock

Closes #4 
Основание для работы с refresh токенами

Refresh tokens

---

DOCKER.md
docker-compose.dev.yml
docker/mongo-init.js

Run
```
docker-compose -f docker-compose.dev.yml exec mongodb bash -c "mongo < /scripts/mongo-init.js"
```

Mongo transactions

---

src/models/membership.js
src/models/team.js
src/models/workspace.js
src/resolvers/index.js
src/resolvers/workspace.js

- Запилены три новые модели
- Можно потестить создание воркспейсов
- получение воркспейсов пользователя или членов воркспейса в следующем реквесте

Workspace, team and membership models

---

.env.sample
docker-compose.dev.yml
src/models/project.js

Project model

---

src/resolvers/user.js
src/typeDefs/user.graphql

Closes #5 
Don't return auth tokens in order to verify user via credentials from email

Email verification fix

---

src/email/providers/EmailProvider.js
src/email/providers/SMTPProvider.js
src/models/project.js
src/models/user.js
src/resolvers/index.js
src/resolvers/project.js
src/resolvers/workspace.js
src/typeDefs/project.graphql

Project resolvers

---

src/email/templates/index.js
src/email/templates/password-reset/html.txt
src/email/templates/password-reset/subject.txt
src/email/templates/password-reset/text.txt
src/models/user.js
src/resolvers/user.js
src/typeDefs/user.graphql

Password reset

---

src/models/membership.js
src/resolvers/workspace.js
src/typeDefs/workspace.graphql

Invite to workspace

---

src/resolvers/project.js
src/typeDefs/event.graphql
src/typeDefs/project.graphql
src/typeDefs/workspace.graphql

Closes #42 
Запрос ошибок:
```graphql
{
workspaces(ids:[]){
id
projects(ids: []){
id
events{
id
catcherType
payload{
title
}
}
}
}
}
```

Event resolver

---

.env.sample
package.json
src/auth.js
src/index.js
src/models/user.js
src/passport.js
src/utils/mongoWatchController.js
yarn.lock

Testing:
- Register GitHub oauth app. Set callback url to `http://localhost:4000/auth/github/callback`
- Copy `.env.sample` to `.env`
- Set `GITHUB_CLIENT_ID` and `GITHUB_CLINET_SECRET` from oauth app
- go to `http://127.0.0.1:4000/auth/github`

GitHub auth

---

src/models/model.js
src/models/user.js
src/models/workspace.js
src/resolvers/workspace.js
src/typeDefs/workspace.graphql
src/utils/objectHasOnlyProps.js
src/utils/validator.js

Workspace settings

---

.env.sample
package.json
src/mongo.js
src/rabbitmq.js
yarn.lock

- Fixed `topology deprecation warning`
- Add AMQP reconnection after fail
- Add MongoDB reconnection after fail

AMQP and MongoDB reconnect

---

package.json
yarn.lock

Copy email templates to build directory
closes #104

Fix email mailing

---

src/resolvers/workspace.js

We do not have a billing service for now, so i removed saving default plan.
Resolves #105

Remove default plan storing with workspace creation

---

src/resolvers/project.js

only admins can create projects

only admins can create projects

---

src/typeDefs/workspace.ts

This change is required for https://github.com/codex-team/hawk.garage/pull/200

Add userId to member schema

---

src/typeDefs/event.ts

For issue [https://github.com/codex-team/hawk.garage/issues/223](https://github.com/codex-team/hawk.garage/issues/223)

Return event type

---

src/resolvers/user.ts

[Fix] Uploading user avatar

---

.env.sample
src/index.ts
src/models/projectsFactory.ts
src/models/user.ts
src/passport.js
src/resolvers/user.ts

[Feature] Different secrets for tokens

---

src/mongo.ts

Return mongo clients for closing connections

[Feature] Return mongo clients

---

migrations/20200803141743-add-plans.js
migrations/20200811174954-create-accounts-for-workspaces.js

Add accounts for workspaces

---

.github/workflows/main.yml

пушим на докерхаб, чтобы избавиться от приватного registry

change workflow for pushing to dockerhub

---

migrations/20200811174954-create-accounts-for-workspaces.js

fix migration for creating accounts

---

src/resolvers/workspace.js

Названия аккаунтов для воркспейсов должны начинаться с WORKSPACE:

fix names for new workspaces

---

.env.sample
src/models/eventsFactory.js
src/resolvers/event.js
src/typeDefs/event.ts

resolves codex-team/hawk.garage#315

Chart for repeated event 

---

.env.sample
src/index.ts
yarn.lock

Update init method for accounting sdk.

[Feature] Update accounting sdk

---

src/resolvers/index.js

Resolves codex-team/hawk.garage#326

Fix incorrect display of addons

---

package.json
src/index.ts
yarn.lock

Adds a check for tls variables. If at least one path is not transmitted, the variable tlsVerify is undefined.

[Feature] Check env variables for tls certs

---

src/resolvers/index.js
src/typeDefs/billing.ts
src/typeDefs/index.ts
src/typeDefs/plans.ts
src/typeDefs/workspace.ts
src/typeDefs/workspaceMutations.ts

resolves https://github.com/orgs/codex-team/projects/10#card-47980015

[balance] Int -> Long

---

src/resolvers/user.ts

The message about existed email is fixed

fix(signup): existed email message improved 

---

.github/workflows/update-monorepository.yml

Sends event that triggers monorepository update

Update monorepository action

---

migrations/20201126110220-add-billingPeriodEventsCount.js
src/typeDefs/workspace.ts

Show total number of errors since the last charge date in workspace billing settings page

feat: add billingPeriodEventsCount field

---

src/models/eventsFactory.js

Сейчас возникает следующая ошибка:
Я добавил костыль, который мы уже [применяли](https://github.com/codex-team/hawk.api.nodejs/blob/master/src/models/eventsFactory.js#L247-L250) и который её фиксит
Мне нужен этот фикс поскорее, так что поставьте аппрувы

fix repetitions fetching

---

migrations/20210126172039-increase-events-limit-on-big-tariff.js

Миграция, которая позволит увеличить лимит ошибок на тарифном плане Big, чтобы наши большие клиенты не страдали от блокировок

increase events limit for Big tariff plan

---

src/billing/index.ts
src/index.ts
src/typeDefs/expressContext.ts
src/types/graphql.ts

Add context to express request so that it can be used in billing and not only

Add context to express request

---

src/billing/cloudpayments.ts
src/billing/types/request.ts
src/dataLoaders.ts
src/models/workspace.ts
src/models/workspacesFactory.ts
test/integration/cases/billing/pay.test.ts
test/models/businessOperation.test.ts
yarn.lock

#276 
+ удалил типы который должны быть в hawk.types, но почему то ещё были в API

New features for `pay` route

---

.env.sample
package.json
src/billing/cloudpayments.ts
src/billing/types/request.ts
src/types/bgTasks.ts
src/utils/telegram.ts
test/integration/cases/billing/check.test.ts
yarn.lock

Logic in the check billing route

Check billing route

---

src/billing/cloudpayments.ts
src/models/workspace.ts
test/integration/accounting.env
test/integration/api.env
test/integration/cases/billing/pay.test.ts
test/integration/docker-compose.yml
test/integration/jestEnv.js
test/integration/utils.ts

[Pay route] Add transactions to accounting

---

src/billing/cloudpayments.ts
src/billing/types/enums/index.ts
src/billing/types/enums/reasonCode.ts
src/billing/types/enums/reasonCodeTranscript.ts
test/integration/cases/billing/fail.test.ts

Add reasons transcript for "payment failed" notification

Reason transcript

---

.huskyrc.js
.lintstagedrc.js
package.json
yarn.lock

We dont need it now as we have github action for it

Remove git hooks for linting

---

package.json
src/billing/cloudpayments.ts
src/billing/types/cardDetails.ts
src/billing/types/ipData.ts
src/billing/types/request.ts
src/dataLoaders.ts
src/models/user.ts
src/models/usersFactory.ts
src/resolvers/userNotifications.ts
src/utils/checksumService.ts
src/utils/personalNotifications.ts
test/integration/cases/billing/check.test.ts
test/integration/cases/billing/fail.test.ts
test/integration/cases/billing/pay.test.ts
test/integration/package.json
test/integration/yarn.lock
yarn.lock

If shouldSaveCard param is true, then the pay route will save the user's bank card 
+ use UserDbScheme from hawk.types

Implement cards saving

---

src/billing/cloudpayments.ts
src/models/user.ts
src/resolvers/billing.js
src/typeDefs/billing.ts
src/typeDefs/user.ts
test/integration/cases/billing/pay.test.ts
yarn.lock

now user can fetch own bank cards

Fetch bank cards and add ids for them

---

jest-mongodb-config.js
package.json
src/models/workspace.ts
test/integration/cases/billing/fail.test.ts
test/integration/cases/billing/pay.test.ts
test/integration/cases/billing/recurrent.test.ts
yarn.lock

[Upgrade] hawk.types

---

.env.test
src/billing/cloudpayments.ts
src/resolvers/billingNew.ts

- старая подписка отменится, если пользователь оформил новую подписку
- текущая подписка отменится, если пользователь оплатил самостоятельно, без подписки (такой кейс в гараже мы не реализуем, но для подстраховки пусть она отменяется)
Также я изменил условие при котором мы списываем с пользователя только нужную для валидация карты сумму
closes #303

Cancel subscription on manual payment or payment via another subscription

---

src/models/workspace.ts
src/models/workspacesFactory.ts
src/resolvers/workspace.js
src/typeDefs/workspace.ts

Workspace factory generates invite hash and adds it to newly created workspace. Workspace query return inviteHash field.

[Feature] Generate invite hash

---

src/models/project.ts

[Fix] Catch error "ns not found"

---

src/index.ts

show debug info only in development env

---

.env.sample
.env.test
jest-mongodb-config.js
package.json
src/billing/cloudpayments.ts
src/index.ts
src/models/eventsFactory.js
src/models/project.ts
src/models/workspace.ts
src/models/workspacesFactory.ts
src/resolvers/billingNew.ts
src/resolvers/event.js
src/resolvers/workspace.js
src/typeDefs/event.ts
src/typeDefs/workspace.ts
test/integration/cases/billing/fail.test.ts
test/integration/cases/billing/pay.test.ts
test/integration/cases/billing/recurrent.test.ts
yarn.lock

[Deploy] Production

---

src/models/workspace.ts

we always should unblock wksp if new plan is applied

Unblock wksp on plan changing

---

src/resolvers/workspace.js
src/typeDefs/event.ts

Title of repetitions will be shown at the Garage's Repetitions List

improvement(repetitions): title and type added to Repetition payload

---

src/resolvers/project.js
src/resolvers/user.ts
src/resolvers/workspace.js
src/typeDefs/project.ts
src/typeDefs/user.ts
src/typeDefs/workspace.ts
src/utils/dates.ts
test/utils/dateFromObjectId.test.ts

I added the function for getting date from object id. Now workspaces, projects, and users can return their creation date.

[Feature] Date from objectid

---

package.json
src/models/user.ts
src/models/workspace.ts
src/resolvers/workspace.js

resolves codex-team/hawk.garage#548

fix: do not add user to wksp without prompt

---

package.json
src/index.ts

resolves [this](https://github.com/codex-team/hawk.garage/issues/564)

CORS added

---

package.json
src/models/workspace.ts

change plan function update to resolve the [issue](https://github.com/codex-team/hawk.garage/issues/545)

`changeplan` updated with tariffPlanId

---

package.json
src/models/workspace.ts
src/resolvers/workspace.js

resolves [bug](https://github.com/codex-team/hawk.garage/issues/547)

Fix Join workspace using invitation link

---

package.json
src/resolvers/event.js
src/resolvers/workspace.js

For Demo Workspace we should not show team and visitedBy

Crutch for demo workspace team

---

package.json
src/models/user.ts
src/resolvers/event.js
src/resolvers/project.js
src/resolvers/user.ts
src/resolvers/workspace.js

logs for multiple events for quick response

User events

---

package.json
src/resolvers/workspace.js

Fixed a log

---

.env.sample
package.json
src/models/usersFactory.ts
src/models/workspacesFactory.ts
src/utils/analytics/amplitude.ts
src/utils/analytics/events.ts
src/utils/analytics/index.ts
yarn.lock

- base module for amplitude
- defined events

Add amplitude analytics

---

package.json
src/models/eventsFactory.js
src/typeDefs/event.ts
src/typeDefs/project.ts

1. Added affected users count to DailyEvents
2. Added sorting daily events by affected users count

feat: added affected users to DailyEvents

---

package.json
src/billing/cloudpayments.ts

Fix error
```
[Billing / Check] TypeError: The loader.load() function must be called with a value, but got: undefined.
```

fix(payments): Fix card linking

---

package.json
src/billing/cloudpayments.ts
src/typeDefs/billing.ts

- Add creating business operation for card linking refund
- Add logs

fix(payments): Progress on recurrent payments

---

package.json
src/models/eventsFactory.js
src/typeDefs/event.ts

added delta to graphql schemas, made repetition payload optional

feat: new diff support

---

package.json
src/billing/cloudpayments.ts
src/models/workspace.ts

this pr is related to new workspaces blocking
check out https://github.com/codex-team/hawk.workers/pull/408

imp(cloudpayments): respect new limiter

---

LICENSE
README.md
package.json

Add LICENSE with Business Source License 1.1 (BSL 1.1).

chore(license): adopt BSL 1.1
