codex-team/hawk.api.nodejs

README.md
migrate-mongo-config.js
migrations/20200224203115-add-index-to-users.js
package.json
src/resolvers/user.ts

[issue-131]: Check email existence

---

src/typeDefs/event.ts

API should response event occurrence time as Unix time so that any client could convert in local timezone. 
Repetition's payload may not contain any fields if the value is equal to the original event payload.

Response timestamp field as unixtime in seconds

---

src/models/eventsFactory.js
src/models/userInProject.js
src/resolvers/project.js

The bug caused by [changing](https://github.com/codex-team/hawk.api.nodejs/pull/158/files#diff-6900e62d5b011b1ae4ee4b04bf2eefeeR20) project resolver to dataloaders by #158

Fix: project child resolvers now use _id instead of id

---

src/resolvers/encodedJSON.ts
src/typeDefs/event.ts
src/typeDefs/index.ts
test/resolvers/encodedJSON.test.ts

see https://github.com/codex-team/hawk.workers/pull/145
так как некоторые поля у ивента теперь могут быть закодированы, то надо парить JSON, прежде чем отдать клиенту данные

create EncodedJSON scalar type and use it on events field

---

.env.sample
package.json
src/billing/cloudpayments.ts
src/billing/types/request.ts
src/index.ts
src/resolvers/billingNew.ts
src/typeDefs/plans.ts
src/utils/checksumService.ts
test/integration/api.env
test/integration/cases/billing/check.test.ts
test/integration/cases/billing/pay.test.ts
test/integration/yarn.lock
yarn.lock

closes #285 
- поправлен формат сообщений от cloudpayments (оказывается там Data в виде строки приходит)
- добавил body-parser чтобы парсить post запросы от CloudPayments
- сделал checksum в виде JWT токена, в котором зашиты все нужные данные, поэтому в Data теперь нужен только он

Fixes for payment widget work

---

src/models/eventsFactory.js
src/resolvers/project.js

If you will change `eventId` in the URL, you will get `Event = null`

fix(event-repetition): return null for 404 event

---

.env.sample
src/models/project.ts
src/models/workspacesFactory.ts
src/resolvers/workspace.js
src/typeDefs/workspace.ts

Now api has two separates mutations:
- `joinByInviteLink` - for joining to a workspace by "public" invite link with invite hash. For example, `https://garage.hawk.so/join/my-invite-hash`;
- `confirmInvitation` - for joining to a workspace by "private" invite link from, for example, email message.

[Feature] Join by invite hash

---

src/resolvers/project.js

у старых проектов нет integration id. Поэтому чтобы обновить токен, им нужно его сгенерировать. Этот реквест позволит генерировать проекту этот id если его нет

generate integration id if not any

---

migrations/20220218172429-user-notifications-fix.js
package.json
src/models/user.ts
src/resolvers/user.ts

Currently, after profile update, all the notifications settings will be overridden by `{ email : 'user email' }` 
This PR fixes that
Resolves #395

fix(profile-settings): notifications settings dropping after profile update

---

package.json
src/resolvers/project.js
src/typeDefs/project.ts

1. Change `project()` query identifier key from `id` to `projectId`
2. Added `@requireUserInWorkspace` directive for `project()` queries

fix: added permission rules to interact with project data

---

package.json
src/billing/cloudpayments.ts

Fix error
```
[Billing / Pay] No workspace, tariff plan or user id in request body
```

fix(payments): card linking error

---

package.json
src/models/project.ts
src/resolvers/index.js
src/resolvers/projectNotifications.ts
src/resolvers/projectPatterns.ts
src/typeDefs/index.ts
src/typeDefs/project.ts
src/typeDefs/projectEventGroupingPattern.ts
src/typeDefs/projectEventGroupingPatternMutations.ts
yarn.lock

- add new project resolver methods for `eventGropingPatterns` resolving
- add new gql type definitions for `eventGroupingPatterns` mutations
- updated `@hawk.so/types` package to use new `DBSchemes` from it
- added new payload types used in new resolver methods 
- removed redundant `ProjectNotificationsRuleDBScheme` type declaration (since it is declared in `@hawk.so/types` package)
- improved some comments related to the notificationRules
this is part of global work on Event Manual Grouping feature, check related prs
GARAGE: https://github.com/codex-team/hawk.garage/pull/677
GROUPER: https://github.com/codex-team/hawk.workers/pull/382
~~TYPES: https://github.com/codex-team/hawk.types/pull/46~~ - already merged

Feat(project-settings): manual event grouping

---

package.json
src/billing/cloudpayments.ts

- Improved logs
- Fixed a bug with prices in history 
- Removed error sending when cancelling subscription

Add log to compose-payment endpoint

---

package.json
src/models/project.ts
src/resolvers/project.js

works with https://github.com/codex-team/hawk.garage/pull/696

feat(notifications-for-all): Setup email notifications for newly created project

---

package.json
src/models/project.ts
src/resolvers/project.js
yarn.lock

Add flag `isAutoAdded` to notification rule meaning that it is created automatically, not by the user

Support autoAdded

---

src/models/eventsFactory.js

Integrated `safe-regex` library to validate user-provided regular expressions and prevent potential ReDoS (Regular Expression Denial of Service) vulnerabilities.
- Added `safe-regex` to check the safety of user-generated search regex patterns.
- If the input regex is considered unsafe (exponential-time), the search will be rejected or skipped.
- Improves overall stability and security of the search endpoint.
User input passed to `$regex` can introduce catastrophic backtracking. This change ensures that only safe regex patterns are used in database queries.
- The validation runs before executing the MongoDB query.

Chore: Use safe-regex to prevent ReDoS in search filter

---

package.json
src/models/project.ts
src/resolvers/projectNotifications.ts
src/typeDefs/projectNotificationsMutations.ts

Add mutation for disabling notifications rule

fix(emails): Support unsubscribe mutation

---

package.json
src/billing/cloudpayments.ts

- Fix recurrent status change emoji
- Fix undefined next payment date for recurrent payment

fix(payments): Improve telegram notifications

---

package.json

#515 breaks the CI https://github.com/codex-team/hawk.api.nodejs/actions/runs/16863401651
It cant find types for `lodash` modules. 
This PR fixes that.

fix(build): fix broken build after new merge

---

package.json
src/typeDefs/event.ts

fixes this issue
https://garage.hawk.so/project/5e5fb64c3e3a9d37fa33739d/event/6848418b8f93dcc91a4110e9/overview
Commits are null most of the time, so resolver should be able to return null as release.commits

fix(): release expectations
